<?php

declare(strict_types=1);

namespace Entelechy\Architect\Support;

use Illuminate\Filesystem\Filesystem;

/**
 * Generates the static, self-contained `docs/storage-contracts.html`
 * reference page summarising every configured storage/file-retention
 * contract in plain language. Regenerated on every
 * `architect:storage:init` run when `storage_contracts.reference_doc.enabled`
 * is true.
 *
 * Intended for three audiences (see STORAGE_CONTRACTS_PLAN.md): the project
 * developer, legal/commercial teams drafting a retention policy, and end
 * users as a transparency page — so the output is a single portable HTML
 * file with inline styling, no external asset dependencies.
 */
final class StorageContractsReferenceDocGenerator
{
    /**
     * @param  array<string, mixed>  $storageContracts  config('architect.storage_contracts') shape
     * @param  array<string, mixed>  $fileRetention  config('architect.file_retention') shape
     */
    public function generate(array $storageContracts, array $fileRetention, ?Filesystem $files = null): string
    {
        $files ??= new Filesystem;
        $path = base_path('docs/storage-contracts.html');

        $files->ensureDirectoryExists(dirname($path));
        $files->put($path, $this->render($storageContracts, $fileRetention));

        return $path;
    }

    /**
     * @param  array<string, mixed>  $storageContracts
     * @param  array<string, mixed>  $fileRetention
     */
    private function render(array $storageContracts, array $fileRetention): string
    {
        $generatedAt = now()->toDayDateTimeString();

        $recordSection = $this->renderRecordContracts($storageContracts);
        $fileSection = $this->renderFileContracts($fileRetention);

        return <<<HTML
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Storage Contracts</title>
        <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 860px; margin: 2rem auto; padding: 0 1.5rem; color: #1f2933; line-height: 1.55; }
            h1 { font-size: 1.75rem; }
            h2 { font-size: 1.25rem; margin-top: 2.5rem; border-bottom: 1px solid #e4e7eb; padding-bottom: 0.4rem; }
            table { width: 100%; border-collapse: collapse; margin: 1rem 0 2rem; }
            th, td { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #e4e7eb; vertical-align: top; }
            th { background: #f5f7fa; font-weight: 600; }
            code { background: #f5f7fa; padding: 0.1rem 0.35rem; border-radius: 3px; font-size: 0.9em; }
            .meta { color: #616e7c; font-size: 0.9rem; }
            .badge { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 999px; font-size: 0.75rem; font-weight: 600; }
            .badge-default { background: #e3f9e5; color: #1b806a; }
            .empty { color: #616e7c; font-style: italic; }
        </style>
        </head>
        <body>
        <h1>Storage Contracts</h1>
        <p class="meta">Generated by <code>architect:storage:init</code> on {$generatedAt}. This page describes how long data is kept at each stage of its lifecycle before being permanently destroyed.</p>
        {$recordSection}
        {$fileSection}
        </body>
        </html>
        HTML;
    }

    /**
     * @param  array<string, mixed>  $storageContracts
     */
    private function renderRecordContracts(array $storageContracts): string
    {
        if (! (bool) ($storageContracts['enabled'] ?? false)) {
            return '<h2>Database Records</h2><p class="empty">Storage Contracts are not enabled for this project.</p>';
        }

        /** @var array<string, array{archived?: string|null, retired?: string|null, cold_storage?: string|null}> $contracts */
        $contracts = (array) ($storageContracts['contracts'] ?? []);
        $default = $storageContracts['default_contract'] ?? null;
        $coldDisk = (string) ($storageContracts['cold_disk'] ?? 'n/a');

        $rows = '';
        foreach ($contracts as $name => $durations) {
            $badge = $name === $default ? ' <span class="badge badge-default">default</span>' : '';
            $archived = e((string) ($durations['archived'] ?? 'n/a'));
            $retired = e((string) ($durations['retired'] ?? 'n/a'));
            $coldStorage = $durations['cold_storage'] ?? null;
            $coldStorageLabel = $coldStorage !== null && $coldStorage !== '' ? e((string) $coldStorage) : 'never (kept in cold storage indefinitely)';

            $rows .= <<<ROW
            <tr>
                <td><code>{$name}</code>{$badge}</td>
                <td>{$archived}</td>
                <td>{$retired}</td>
                <td>{$coldStorageLabel}</td>
            </tr>
            ROW;
        }

        return <<<HTML
        <h2>Database Records</h2>
        <p>Every record under a contract passes through four stages: <strong>Archived</strong> (soft-deleted, restorable), <strong>Retired</strong> (marked for permanent removal, still restorable up to this point), <strong>Cold Storage</strong> (the record is serialized and moved to the <code>{$coldDisk}</code> disk, then permanently removed from the database — restore is no longer possible), and <strong>Purged</strong> (the cold storage copy itself is deleted; only a minimal historical marker remains).</p>
        <table>
            <thead><tr><th>Contract</th><th>Archived for</th><th>Then Retired for</th><th>Then in Cold Storage for</th></tr></thead>
            <tbody>{$rows}</tbody>
        </table>
        HTML;
    }

    /**
     * @param  array<string, mixed>  $fileRetention
     */
    private function renderFileContracts(array $fileRetention): string
    {
        if (! (bool) ($fileRetention['enabled'] ?? false)) {
            return '<h2>Uploaded Files</h2><p class="empty">File Retention is not enabled for this project.</p>';
        }

        /** @var array<string, array{inactive?: string|null, purge?: string|null}> $contracts */
        $contracts = (array) ($fileRetention['contracts'] ?? []);
        $default = $fileRetention['default_contract'] ?? null;

        $rows = '';
        foreach ($contracts as $name => $durations) {
            $badge = $name === $default ? ' <span class="badge badge-default">default</span>' : '';
            $inactive = e((string) ($durations['inactive'] ?? 'n/a'));
            $purge = $durations['purge'] ?? null;
            $purgeLabel = $purge !== null && $purge !== '' ? e((string) $purge) : 'never (soft-deleted files are kept indefinitely)';

            $rows .= <<<ROW
            <tr>
                <td><code>{$name}</code>{$badge}</td>
                <td>{$inactive}</td>
                <td>{$purgeLabel}</td>
            </tr>
            ROW;
        }

        return <<<HTML
        <h2>Uploaded Files</h2>
        <p>Uploaded/attached files are tracked by last-accessed time rather than record age: <strong>Active</strong> (recently accessed), <strong>Soft-deleted</strong> (unaccessed for the contract's "inactive" duration; flagged but not yet removed from disk), and <strong>Permanently removed</strong> (deleted from disk after the "purge" duration with no further access).</p>
        <table>
            <thead><tr><th>Contract</th><th>Inactive for</th><th>Then Soft-deleted for</th></tr></thead>
            <tbody>{$rows}</tbody>
        </table>
        HTML;
    }
}
