<?php

use Entelechy\Architect\Permissions\AllowAllPermissionResolver;
use Entelechy\Architect\Tenancy\NullTenantResolver;

return [
    'setup' => [
        'initialized' => false,
        'version' => 1,
        'locks' => [
            // hard: cannot be changed after init without --break-glass
            'hard' => ['persistence_mode', 'tenancy_mode', 'state_table'],
            // soft: can be changed with --force-reconfigure
            'soft' => ['state_connection', 'auth_guard'],
        ],
        'chosen' => [
            'persistence_mode' => null, // localStorage | database
            'tenancy_mode' => null,     // single | multi
            'state_table' => null,
            'state_connection' => null, // null = default db connection
            'auth_guard' => null,
        ],
    ],

    'auth_guard' => env('ARCHITECT_AUTH_GUARD', 'web'),

    'permissions' => [
        'resolver' => AllowAllPermissionResolver::class,
    ],

    'lookup_route' => 'architect.lookup',

    'table' => [
        'per_page' => 25,
        'per_page_options' => [10, 25, 50, 100],
        'empty_state_text' => 'No records found.',
        'search_debounce' => 400,
    ],

    'asset_version' => env('ARCHITECT_ASSET_VERSION', '1'),

    'toast' => [
        'position' => 'bottom-right',
        'duration' => 4000,
    ],

    'notifications' => [
        'driver' => 'database',
        'polling_interval' => '30s',
        'centre_max_items' => 50,
    ],

    'playground' => [
        'enabled' => env('ARCHITECT_PLAYGROUND', false),
    ],

    /*
    |--------------------------------------------------------------------------
    | Animations
    |--------------------------------------------------------------------------
    | Master switch for all UI animations. Set to false to disable all
    | animations package-wide (e.g. for accessibility-first deployments).
    | Individual animations can also be controlled per-definition via the
    | ->animateRows(), ->animatePanels(), ->animateErrors(), ->animateButtons()
    | methods on TableBuilder, and ->countUp() on MetricCard.
    |
    | Note: prefers-reduced-motion is always respected regardless of this flag.
    |
    */
    'animations' => true,

    'features' => [
        'tables' => true,
        'navigator' => true,
        'toolbar' => true,
        'stats' => true,
        'supersearch' => true,
        'forms' => true,
        'notifications' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Import Subsystem
    |--------------------------------------------------------------------------
    | Database connection and table names for architect_import_batches.
    | Set 'connection' to null to use the default database connection.
    | Host apps using an existing table can override 'table' and 'items_table'
    | to point at their legacy tables and skip the package migration.
    */
    'import' => [
        'connection' => null,   // null = config('database.default')
        'table' => 'architect_import_batches',
        'items_table' => 'architect_import_batch_items',
    ],

    /*
    |--------------------------------------------------------------------------
    | Forms
    |--------------------------------------------------------------------------
    | 'discovery.paths' is scanned by `php artisan architect:forms:audit-keys`
    | for classes exposing a static definition(): ArchitectFormDefinition|
    | ArchitectWizardDefinition method, to detect duplicate form/wizard keys
    | project-wide. Defaults to app_path() when left empty.
    |
    | 'draft_ttl_days' controls how long CacheWizardDraftStore (the default
    | WizardDraftStore binding) retains an in-progress wizard's draft state.
    */
    'forms' => [
        'discovery' => [
            'paths' => [],
        ],
        'draft_ttl_days' => 7,
    ],

    /*
    |--------------------------------------------------------------------------
    | Doctor
    |--------------------------------------------------------------------------
    | 'discovery.paths' is scanned by `php artisan architect:doctor`'s
    | DefinitionInterfaceAuditor check for classes exposing a static
    | definition()/build() method across every subsystem (Table, Content,
    | Stats, Panels, Forms, Wizard, Toolbar, Supersearch, Navigator), to
    | verify each implements its required Provides*Definition marker
    | interface. Defaults to app_path() when left empty.
    */
    'doctor' => [
        'discovery' => [
            'paths' => [],
        ],
    ],

    'state' => [
        // Runtime persistence mode selected by architect:init.
        'mode' => 'localStorage',
        // Database connection for persisted user state. Null = default.
        'connection' => null,
        // Host-app migration generated by architect:init uses this table name.
        'table' => 'architect_user_states',
    ],

    /*
    |--------------------------------------------------------------------------
    | Tenancy
    |--------------------------------------------------------------------------
    | FQCN of the class implementing \Entelechy\Architect\Contracts\TenantResolver.
    | Defaults to NullTenantResolver (resolve() returns an empty, connection-less
    | TenantContext — single-tenant). Multi-tenant host apps implement their own
    | resolver returning a Tenancy\TenantContext: set ->identifier for row-level
    | scoping (models implementing Tenancy\Contracts\HasTenantScope), and/or
    | ->connection for database-per-tenant connection switching (e.g. bridging
    | stancl/tenancy's already-resolved tenant connection).
    */
    'tenant' => [
        'resolver' => NullTenantResolver::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Storage Contracts
    |--------------------------------------------------------------------------
    | Named retention contracts for the DB-record lifecycle: Archived (existing
    | SoftDeletes, unchanged) -> Retired -> Cold Storage -> Purged. Disabled by
    | default — Cold Storage and Purge are destructive/irreversible, so this
    | must be an explicit, deliberate opt-in. Configure via
    | `php artisan architect:storage:init`; do not hand-edit `contracts` below.
    |
    | Each contract entry: ['archived' => '2 years', 'retired' => '1 year',
    | 'cold_storage' => '1 year']. A 'cold_storage' duration of null/absent
    | means "never auto-purge" for that contract. Exactly one contract must be
    | named by 'default_contract'.
    */
    'storage_contracts' => [
        'enabled' => false,
        'cold_disk' => null,
        'default_contract' => null,
        'contracts' => [],
        'ledger' => [
            'connection' => null, // null = config('database.default')
            'table' => 'architect_storage_ledger',
        ],
        'reference_doc' => [
            'enabled' => false, // generates docs/storage-contracts.html when true
        ],
        'discovery' => [
            // Required, no implicit default: FQCNs or PSR-4 directories that
            // `architect:storage:discover` scans for *Definition classes
            // (a static definition(): ArchitectTableDefinition method), used
            // to auto-infer FileUpload columns per model. Must be set
            // explicitly by the host app.
            'paths' => [],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | File Retention
    |--------------------------------------------------------------------------
    | Named retention contracts for uploaded/attached files, tracked by
    | last-accessed time rather than record age: Inactive -> Soft-deleted ->
    | Permanently removed (no Cold Storage stage for files). Disabled by
    | default. Configure via `php artisan architect:storage:init`.
    |
    | Each contract entry: ['inactive' => '1 year', 'purge' => '6 months'].
    | A 'purge' duration of null/absent means soft-deleted files persist
    | indefinitely (never auto-purged).
    */
    'file_retention' => [
        'enabled' => false,
        'default_contract' => null,
        'contracts' => [],
        'ledger' => [
            'connection' => null, // null = config('database.default')
            'table' => 'architect_uploads',
        ],
    ],
];
